development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: googlizer_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: googlizer_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: googlizer_production
  pool: 5
